AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  github-actions-with-aws-sam

  Sample SAM Template for github-actions-with-aws-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
  MessageQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "lambda-test-queue"

  Tables:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: stacks/tables.yaml

  Roles:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: stacks/roles.yaml
      Parameters:
        TableArn: !GetAtt Tables.Outputs.TableArn
        MessageQueueArn: !GetAtt MessageQueue.Arn

  Function:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: stacks/functions.yaml
      Parameters:
        FunctionsRole: !GetAtt Roles.Outputs.Arn
        MessageQueueArn: !GetAtt MessageQueue.Arn

  StateMachine:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: stacks/state_machine.yaml
      Parameters:
        lambdaArn: !GetAtt Function.Outputs.helloWorldArn



#Outputs:
#  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
#  # Find out more about other implicit resources you can reference within SAM
#  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#  HelloWorldApi:
#    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello-js/"
#  HelloWorldTSFunction:
#    Description: "Hello World Lambda Function ARN"
#    Value: !GetAtt HelloWorldTSFunction.Arn
#  HelloWorldTSFunctionIamRole:
#    Description: "Implicit IAM Role created for Hello World function"
#    Value: !GetAtt HelloWorldTSFunction.Arn
#  QueueName:
#    Description: "Queue name is"
#    Value: !GetAtt MessageQueue.QueueName
#  QueueARN:
#    Description: "Queue ARN is"
#    Value: !GetAtt MessageQueue.Arn

