service: aws-node-project

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1

functions:
  hello:
    handler: app.lambdaHandler
    events:
      - httpApi: 'GET /test'

resources:
  Resources:
    MessageQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: "lambda-test-queue"

plugins:
  - serverless-offline
  - serverless-plugin-typescript
