service: aws-node-project

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: app.lambdaHandler

plugins:
  - serverless-offline
  - serverless-plugin-typescript
