Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "Channel"
          AttributeType: "S"
        - AttributeName: "Event"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "Channel"
          KeyType: "HASH"
        - AttributeName: "Event"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "Events"

Outputs:
  TableArn:
    Value: !GetAtt DynamoDBTable.Arn
    Export:
      Name: TableArn